### ISSUE TITLE
methodname

### ISSUE THREAD

**Issue by Ferdie-11** [Ferdie-11/ESTALLO-LAGDAAN-ALLANIGUE_LAB3#1]
The method displayMenu is undefined for the type clock, so please add method to display the option.
Thank You.

**Comment by markko17** [comment]
> The method displayMenu is undefined for the type clock, so please add method to display the option. Thank You.
Done adding a display method and configuring menu for choosing a conversion. 😘😘😘😘😘😘😘😘😘😘😘😘
